services:
  cyprus1:
    image: "macochen/quai-network:latest"
    env_file:
      - network.env
    environment:
      - TCP_PORT=30307
      - HTTP_PORT=8610
      - WS_PORT=8611
      - COINBASE_ADDR=${COINBASE_ADDR}
      - PUB_IP=${PUB_IP}
    command: sh -c './build/bin/go-quai --$$NETWORK --slices "$$SLICES" --syncmode full --http --http.vhosts=* --ws --miner.etherbase $$COINBASE_ADDR --http.addr 0.0.0.0 --http.api eth,net,web3,quai,txpool,debug --ws.addr 0.0.0.0 --ws.api eth,net,web3,quai,txpool,debug --port $$TCP_PORT --http.port $$HTTP_PORT --nat extip:$$PUB_IP --ws.port $$WS_PORT --ws.origins=* --http.corsdomain=* --gcmode archive --nonce $$NONCE --region 0 --zone 0 --dom.url ws://cyprus:8579'
    ports:
      - "30307"
      - "8610"
      - "8611"
    volumes:
      - ~/.quai:/root/.quai
      - ~/nodelogs:/go-quai/nodelogs
